# Generated by Django 4.1.5 on 2023-02-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmhub_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlesson',
            name='status',
            field=models.TextField(choices=[('Assigned', 'Assigned'), ('Completed', 'Completed'), ('Confirmed', 'Confirmed')], default='Assigned'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(),
        ),
    ]
