# Generated by Django 4.1.5 on 2023-03-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmhub_app', '0002_alter_studentlesson_status_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='num_repetitions',
            field=models.IntegerField(default=1),
        ),
    ]
