# Generated by Django 4.1.5 on 2023-03-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmhub_app', '0002_alter_studentlesson_status_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audio',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='has_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
