# Generated by Django 4.1.5 on 2023-03-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmhub_app', '0003_lesson_num_repetitions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='num_repetitions',
        ),
        migrations.AddField(
            model_name='studentlesson',
            name='num_repetitions',
            field=models.IntegerField(default=1),
        ),
    ]
