# Generated by Django 4.1.5 on 2023-03-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilmhub_app', '0003_alter_lesson_audio_alter_lesson_has_image'),
        ('ilmhub_app', '0004_remove_lesson_num_repetitions_and_more'),
    ]

    operations = [
    ]
