# Generated by Django 4.1.5 on 2023-03-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmhub_app', '0004_remove_lesson_num_repetitions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audio',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='text',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentlesson',
            name='status',
            field=models.TextField(choices=[('Assigned', 'Assigned'), ('Completed', 'Completed'), ('Confirmed', 'Confirmed'), ('Marked For Redo', 'Marked For Redo')], default='Assigned'),
        ),
    ]
