# Generated by Django 4.1.5 on 2023-03-16 23:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmhub_app', '0005_alter_lesson_audio_alter_lesson_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audio',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='text',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=''),
        ),
    ]
