# Generated by Django 4.1.5 on 2023-03-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilmhub_app', '0006_alter_lesson_audio_alter_lesson_has_image_and_more'),
        ('ilmhub_app', '0006_alter_lesson_audio_alter_lesson_text'),
    ]

    operations = [
    ]
